### ISSUE TITLE
clang-format commits create a lot of noise

### ISSUE THREAD

**Issue by ojura** [googlecartographer/infrastructure#12]
Recently you started updating all PRs with clang-format commits very often. I think this creates a lot of noise in Github notifications. Could you revert to running clang-format only at the point of merging?

**Comment by SirVer** [comment]
Sorry for the noise bomb. That happened because wally switched hosts and the other host did have a different version of clang-format.

No, we specifically want all PRs to be automatically formatted consistently at all points in time. This removes the burden from the reviewers of reviewing badly formatted code and from contributors to learn and install clang-format. Wally will only ever do one commit and if nothing changes, it will do nothing. As said, this bomb today was hopefully a one time event.

**Comment by ojura** [comment]
Okay, but I still think that the clang-format bot is pushing unnecessary stuff. Consider this commit, which was pushed into one PR of mine: https://github.com/googlecartographer/cartographer/pull/553/commits/70aecf9ccb0e902af50a3c0f22e25e7d4473d0de

There is still a lot of unrelated reformatting in that commit. Maybe run clang-format only on files modified in the PR?
